# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: application-inspector-devops-plugin@1
  inputs:
    serverAddress: 'https://aie-ub2204-30145.aie.ptsecurity.ru/'
    token: 'E+hdWHi4AL/7yPkWaoRzYce1WvQsbABQ'
    actionMode: 'scan'
    settingsType: 'enterNew'
    newSettings: |
      {
          "ProjectName": "Muzychenko-qa/test",
          "ProgrammingLanguage": "Php",
          "ScanModules": [
              "VulnerableSourceCode",
              "DataFlowAnalysis",
              "PatternMatching",
              "Components",
              "Configuration"
          ],
          "CustomParameters": null,
          "UseSastRules": false,
          "UseCustomPmRules": false,
          "UseSecurityPolicies": false,
          "SkipGitIgnoreFiles": false,
          "UsePublicAnalysisMethod": false,
          "DownloadDependencies": true,
          "MailingProjectSettings": {
              "Enabled": false,
              "MailProfileName": null,
              "EmailRecipients": []
          }
      }